# BEGIN boilerplate-managed
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/build"
    labels:
      - "area/dependency"
      - "ok-to-test"
      - "lgtm"
      - "approved"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    ignore:
      - dependency-name: "ubi9/go-toolset"
        # builder go-toolset base is pinned in Dockerfile, not via Dependabot
# END boilerplate-managed
