apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  name: webhook-cert
  namespace: validation-webhook
# data.(service-ca.crt) is filled in by openshift-ca-operator
data: {}
