apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: validation-webhook
    deployment: validation-webhook
  name: validation-webhook
  namespace: validation-webhook
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: validation-webhook
    spec:
      serviceAccountName: validation-webhook
      containers:
      - image: quay.io/lseelye/python3-webhookbase:latest
        imagePullPolicy: Always
        command: 
        - gunicorn
        - --config
        - /app/gunicorn.py
        - --ca-certs
        - /service-ca/service-ca.crt
        - --keyfile
        - /service-certs/tls.key
        - --certfile
        - /service-certs/tls.crt
        - --access-logfile
        - "-"
        - webhook:app
        name: validation-webhook
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: service-certs
          mountPath: /service-certs
          readOnly: true
        - name: service-ca
          mountPath: /service-ca
          readOnly: true
      restartPolicy: Always
      volumes:
        - name: service-certs
          secret:
            secretName: webhook-cert
        - name: service-ca
          configMap:
            name: webhook-cert
