apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: webhook-cert
    cert-manager.io/inject-apiserver-ca: "true"
  name: validation-webhook
  namespace: validation-webhook
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 5000
  selector:
    app: validation-webhook
  type: ClusterIP
