apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata: 
  annotations:
    cert-manager.io/inject-apiserver-ca: "true"
    cert-manager.io/inject-ca-from: validation-webhook/webhook-cert
  name: sre-validate-webhook
  namespace: ""
webhooks:
  - clientConfig:
      service:
        namespace: validation-webhook
        name: validation-webhook
      caBundle: ""
    failurePolicy:
      "Fail"
    name: "validate.group.change"
    rules: 
      - operations: 
          - "UPDATE"
          - "CREATE"
          - "DELETE"
        apiGroups: 
          - "user.openshift.io"
        apiVersions: 
          - "*"
        resources: 
          - "groups"
        scope: 
          "Namespaced"