apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/managed-cluster-validating-webhooks?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: 'false'
    pipelinesascode.tekton.dev/max-keep-runs: '3'
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "master"
  labels:
    appstudio.openshift.io/application: managed-cluster-validating-webhooks
    appstudio.openshift.io/component: managed-cluster-validating-webhooks-pko
    pipelines.appstudio.openshift.io/type: build
  name: managed-cluster-validating-webhooks-pko-on-push
  namespace: managed-cluster-validating-webhooks-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/managed-cluster-validating-webhooks-tenant/openshift/managed-cluster-validating-webhooks-pko:{{revision}}
  - name: dockerfile
    value: Dockerfile.pko
  - name: path-context
    value: config/package
  - name: build-args
    value:
    - VERSION={{revision}}
    - RELEASE={{revision}}
  - name: skip-preflight-cert-check
    value: 'true'
  taskRunTemplate:
    serviceAccountName: build-pipeline-managed-cluster-validating-webhooks-pko
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/openshift/boilerplate
    - name: revision
      value: 5b58d5f28eb2b26c90caf079e1b052a8b1d03db0
    - name: pathInRepo
      value: pipelines/docker-build-oci-ta/pipeline.yaml
status: {}
